### ISSUE TITLE
unable to set up cluster on ubuntu 20

### ISSUE THREAD

**Issue by asagarshinde** [ddometita/mmumshad-kubernetes-the-hard-way#4]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet4", "--ip", "192.168.5.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

**Comment by asagarshinde** [comment]
chaged ip from 192.168.5. to 192.168.56. and it is working

ref:- https://discuss.hashicorp.com/t/vagrant-2-2-18-osx-11-6-cannot-create-private-network/30984/5

**Comment by ricardosilva86** [comment]
remember to close issues that are no longer and issue
